name: BUILD

on:
  workflow_dispatch:
  push:

jobs:
  build-project:
    name: Build Project
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # - name: Setup Ninja
    #   uses: seanmiddleditch/gha-setup-ninja@v5
     
    # - name: cmake
    #   uses: threeal/cmake-action@v2.0.0
    #   with:
    #     # generator: Ninja
    #     build-dir: build
    #     options: |
    #       CMAKE_BUILD_TYPE=Release

    - name: cmake
      uses: lukka/run-cmake@v10
      with:
        # generator: Ninja
        buildPresetAdditionalArgs: "['--config Release']"

    - run: python package-plugin.py

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "release"
        artifacts: "./HealthNotes.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
