name: BUILD

on:
  workflow_dispatch:

jobs:
  build-project:
    name: Build Project
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cmake
      uses: threeal/cmake-action@v2.0.0
      with:
        build-dir: build
      options: |
        CMAKE_BUILD_TYPE=Release
    - run: python package-plugin.py

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "release"
        artifacts: "./HealthNotes.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
